name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bs-cs410/daisy-docker-image
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DBUILD_DOCS=OFF -B build

      - name: Build
        run: cmake --build build --config Debug --parallel 4

      - name: Configure-Docs
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DBUILD_DOCS=ON -B build

      - name: Build-Docs
        run: cmake --build build --config Debug --target docs --parallel 4

      - name: Tests
        run: xvfb-run ctest --test-dir build --output-on-failure